Repository Enigmatic-Smile/docs, pull requests merged in 2023-02, with the labels that each got.

#205 [PAY-846] update fidel webhooks docs with reimbursement webhooks
  webhooks.md
Labels: documentation

#206 [TXNR-166][PATCH] Adapting the metadata API card documentation
  cards.md
Labels: enhancement

#196 [PAY-1514] add UK/GBR as supported country in reimbursement offer automation
  reimbursement.md
Labels: enhancement, documentation

#208 [PAY-2059] replace reimbursement-transaction-not-found error [MINOR]
  reimbursement.md
Labels: enhancement

#204 [DOC-38] Removing links to the Community Forum [PATCH]
  index.md
  locations.md
  mobile-sdks.md
  webhooks.md
Labels: enhancement
