Repository Enigmatic-Smile/docs, pull requests merged in 2023-01, with the labels that each got.

#200 [TXNR-82][PATCH] Improve webhooks documentation
  webhooks.md
Labels: enhancement

#201 [TXNR-86][PATCH] Refactoring specific header/key references
  brands.md
  cards.md
  locations.md
  offers.md
  programs.md
  reimbursement.md
  transactions.md
Labels: bug, enhancement

#202 [PATCH][MO-890] Fix broken link to reference
  brands.md
  cards.md
  locations.md
  offers.md
  programs.md
  reimbursement.md
  transactions.md
  web-sdk/v2.md
  web-sdk/v3.md
  webhooks.md
Labels: bug

#203 [PAY-2004] remove reimbursementEligible field [MINOR]
  reimbursement.md
  transactions.md
Labels: documentation
